name: legit_cards
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  web: ^1.0.0

  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  # For Firebase Cloud Messaging (FCM)
#  firebase_core: ^2.32.0   #old version
#  firebase_messaging: ^14.2.0  #old version

  http: ^1.2.2

  provider: ^6.1.2
  go_router: ^14.8.1
  fluttertoast: ^8.2.8
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.0.0
  encrypt: ^5.0.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  device_info_plus: ^10.1.0
  # help pick image from gallery and handle permission
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  cached_network_image: ^3.3.1
  # compress image
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.9.0
  # upload image to cloud
  cloudinary_public: ^0.23.1
  #qr code
  qr_flutter: ^4.1.0
  #real-time firebase database and auth
  firebase_database: ^11.0.0
  firebase_auth: ^5.3.0
  # for local notification
#  flutter_local_notifications: ^15.1.0  # Change from 16.3.3 to 15.1.0
  awesome_notifications: ^0.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/long_logo.png
    - assets/images/trans_logo.png
    - assets/images/trans_logo2.png
#    - assets/icons/verify_edu_badge.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
